name: "Setup Xcode"
description: "Setup specific Xcode version for iOS builds"
inputs:
  xcode-version:
    description: "Xcode version to use"
    required: false
    default: "16.4.0"

runs:
  using: "composite"
  steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}

    - name: Download iOS Platform
      run: xcodebuild -downloadPlatform iOS
      shell: bash
